# architecture
model_name: lalqr 
num_enc_layers: 2
enc_dim: 512
mlp_dim: 512
latent_dim_internal: 100
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 1
vmin: -10
vmax: +10

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# training 
batch_size: 512 # 256 when imitating tdmpc2
reward_coef: 0.1
value_coef: 0.0 # 0.1
consistency_coef: 20
lr: 1e-3
grad_clip_norm: 20
rho: 0.5
num_noises: 10
std_noises: 0.5
temperature_noises: 0.5
loss_type: kl

dynamic_structure: full
cost_structure: full
